# Generated by Django 5.2 on 2025-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourTodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
